[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "target-feature=+crt-static",
    "-L", "C:\\Projects\\3rd\\sciter\\work\\lib\\windows\\x64",
    "-l", "Comdlg32",
    "-l", "windowscodecs",
    "-l", "Wininet",
    "-l", "gdi32",
    "-l", "Winspool",
    ]